### ISSUE TITLE
Fetch Budget from YNAB API

### ISSUE THREAD

**Issue by rraabe** [DoctorGrim/YNAB-google-assistant#3]
Determine the syntax and required data to fetch a users specific budget. 

Right now using a client ID

Need in the future to use OAuth token so that clients do not need to sign up individually.

----------------------------------------

As a Server User

Given that I pull the branch and use my personal access token for YNAB API.

When I visit the "http://localhost:3000/".
And I authorize my access token to use YNAB API.
And I configure a 'default' budget.
And  I press a button 'budget month'.

Then I see all my categories, balance, and budget and in the **Browser Console**.
And my personal categories and values are present in the output.

**Comment by bradymholt** [comment]
During our call yesterday I mentioned using the `GET /budgets/{budget_id}/categories` endpoint but I think using `GET /budgets/{budget_id}/months/{month}` might be easier to work with because the categories are wrapped in groups so it is less to parse.  Here is an example using the `ynab` package for how to get category balances

```
const ynab = require("ynab");
const accessToken ="abc123xyz";
const ynabAPI = new ynab.API(accessToken);

 // "last-used" is a psuedo budgetId for referencing the last used budget
const budgetId = "last-used";
const month = "current"

const budgetMonthRequest = ynabAPI.months.getBudgetMonth(budgetId, month);
budgetMonthRequest.then(r => {
  const categories = r.data.month.categories;
  const balances = categories.map(c => {
    return {
      name: c.name,
      // we need to convert the milliunits balance to a currency amount first
      balance: ynab.utils
        .convertMilliUnitsToCurrencyAmount(c.balance, 2)
        .toFixed(2)
    };
  });
  console.log(balances);
  /*
    Example output:
    [
      { name: 'Medical', balance: '77.00' },
      { name: 'Fitness', balance: '4.00' },
      { name: 'Gifts', balance: '29.00' },
      { name: 'gas', balance: '15.00' },
      { name: 'Student Loan', balance: '21.00' },
      ...
    ]
  */
});
```

**Comment by bradymholt** [comment]
As mentioned on our call yesterday, an easy way to specify a budget when using the API is to enable "default budget selection" on the OAuth application:

![image](https://user-images.githubusercontent.com/759811/62786870-1c530700-ba89-11e9-8442-29f3bf5bdaeb.png)

When you do this, the user will be prompted to select a default budget when going through the OAuth flow:

![image](https://user-images.githubusercontent.com/759811/62786919-3260c780-ba89-11e9-9779-362c19aa8f3b.png)

Then, when hitting the API, you can simple use "default" in lieu of an actual budget ID.  Documentation is located here: https://api.youneedabudget.com/#oauth-default-budget.

Also, another simple way to handle this is to simply pass in "last-used" which will reference the last used budget.  This might be a better place to start since it's simpler.
